# Generated by Django 4.2.4 on 2023-09-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(default='cup', max_length=50),
            preserve_default=False,
        ),
    ]
