# Generated by Django 4.2.4 on 2023-09-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('cup', 'Cups'), ('decoration', 'Decorations'), ('shirt', 'Shirts')], default='', max_length=10)),
                ('inventory', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
