# Generated by Django 4.2.4 on 2023-09-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/shop'),
            preserve_default=False,
        ),
    ]
