# Generated by Django 4.2.4 on 2023-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
